"""adds wallet address

Revision ID: 0015f16df889
Revises: c31ddd7c0574
Create Date: 2025-10-06 10:22:32.756268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0015f16df889'
down_revision: Union[str, None] = 'c31ddd7c0574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'wallet_address')
    # ### end Alembic commands ###
