"""Add email row

Revision ID: 6fdbcc56aa7e
Revises: 1e7e1107c84a
Create Date: 2025-08-18 11:49:29.908320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdbcc56aa7e'
down_revision: Union[str, None] = '1e7e1107c84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
