"""Add blockchain fields to groups

Revision ID: fbfdb8d62149
Revises: 6fdbcc56aa7e
Create Date: 2025-08-24 12:38:09.566274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfdb8d62149'
down_revision: Union[str, None] = '6fdbcc56aa7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('contract_address', sa.String(length=42), nullable=True))
    op.add_column('groups', sa.Column('creation_tx_hash', sa.String(length=66), nullable=True))
    op.add_column('groups', sa.Column('creation_block_number', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('network_id', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('is_blockchain_synced', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('last_blockchain_sync', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_groups_contract_address'), 'groups', ['contract_address'], unique=True)
    op.create_unique_constraint(None, 'groups', ['creation_tx_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_index(op.f('ix_groups_contract_address'), table_name='groups')
    op.drop_column('groups', 'last_blockchain_sync')
    op.drop_column('groups', 'is_blockchain_synced')
    op.drop_column('groups', 'network_id')
    op.drop_column('groups', 'creation_block_number')
    op.drop_column('groups', 'creation_tx_hash')
    op.drop_column('groups', 'contract_address')
    # ### end Alembic commands ###
